In [3]:
import numpy as np
import pandas as pd

## Importing Data

In [10]:
# pip install xlrd
!pip install xlrd==1.2.0

In [23]:
import pandas as pd
df = pd.read_excel('Agenciesandcodes1.xlsx')

print(df)

     11.11.01  11.11.06  11.11.07  11.11.14  11.11.33  11.12.01  11.12.02  \
0         NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1         NaN       NaN       NaN       NaN       NaN       NaN       1.0   
2         NaN       NaN       NaN       NaN       NaN       5.0       9.0   
3         NaN       NaN       NaN       NaN       NaN       NaN       3.0   
4         NaN       NaN       NaN       NaN       NaN       1.0       2.0   
..        ...       ...       ...       ...       ...       ...       ...   
885       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
886       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
887       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
888       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
889       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

     11.12.03  11.12.04  11.12.06  ...  70.49.00  70.50.00  70.65.00  \
0  

In [25]:
df1=df.fillna(0)
df1.head()

11.11.01  11.11.06  11.11.07  11.11.14  11.11.33  11.12.01  11.12.02  \
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       1.0   
2       0.0       0.0       0.0       0.0       0.0       5.0       9.0   
3       0.0       0.0       0.0       0.0       0.0       0.0       3.0   
4       0.0       0.0       0.0       0.0       0.0       1.0       2.0   

   11.12.03  11.12.04  11.12.06  ...  70.49.00  70.50.00  70.65.00  74.10.01  \
0       1.0      20.0       0.0  ...       0.0       0.0       0.0       0.0   
1       4.0      36.0       0.0  ...       0.0       0.0       0.0       0.0   
2       5.0       6.0       0.0  ...       0.0       0.0       0.0       4.0   
3       0.0       4.0       0.0  ...       0.0       0.0       0.0       0.0   
4       0.0      17.0       0.0  ...       0.0       0.0       0.0       1.0   

   74.10.02  74.10.03  74.10.04  74.10.05  74.10.06  74.10.10  
0       0.0       0.0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0       0.0       0.0  
2       4.0       4.0       0.0       3.0       0.0       0.0  
3       0.0       0.0       0.0       0.0       0.0       0.0  
4       1.0       1.0       0.0       1.0       0.0       0.0  

[5 rows x 633 columns]

In [26]:
# calculate co-occurrence matrix
x = np.array(df1)
y = np.array(df1.T)
co_matrix = np.dot(y,x)
np.fill_diagonal(co_matrix, 0)
co_matrix

array([[ 0.,  2.,  0., ...,  0.,  0.,  0.],
       [ 2.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0., 10., 30.],
       [ 0.,  0.,  0., ..., 10.,  0.,  4.],
       [ 0.,  0.,  0., ..., 30.,  4.,  0.]])

In [27]:
#show the co-occurance matrix as a dataframe 
df1_asint = df1.astype(int)
coocc = df1_asint.T.dot(df1_asint)
coocc

11.11.01  11.11.06  11.11.07  11.11.14  11.11.33  11.12.01  \
11.11.01         7         2         0         2         4        22   
11.11.06         2         1         0         1         2         5   
11.11.07         0         0         1         0         0         1   
11.11.14         2         1         0         1         2         5   
11.11.33         4         2         0         2         7        14   
...            ...       ...       ...       ...       ...       ...   
74.10.03         0         0         0         0         2       101   
74.10.04         0         0         0         0         0         2   
74.10.05         0         0         0         0         0        31   
74.10.06         0         0         0         0         0        13   
74.10.10         0         0         0         0         0        10   

          11.12.02  11.12.03  11.12.04  11.12.06  ...  70.49.00  70.50.00  \
11.11.01         1         0         2         6  ...         0         0   
11.11.06         0         0         0         3  ...         0         0   
11.11.07         0         0         0         0  ...         0         0   
11.11.14         0         0         0         3  ...         0         0   
11.11.33         9         6        37         6  ...         0         0   
...            ...       ...       ...       ...  ...       ...       ...   
74.10.03       184       170       769         0  ...         0         0   
74.10.04        17        26        33         0  ...         0         0   
74.10.05        85        75       263         0  ...         0         0   
74.10.06        36        29        98         0  ...         0         0   
74.10.10        38        31        52         0  ...         0         0   

          70.65.00  74.10.01  74.10.02  74.10.03  74.10.04  74.10.05  \
11.11.01         0         0         0         0         0         0   
11.11.06         0         0         0         0         0         0   
11.11.07         0         0         0         0         0         0   
11.11.14         0         0         0         0         0         0   
11.11.33         0         0         2         2         0         0   
...            ...       ...       ...       ...       ...       ...   
74.10.03         0       185       159       219        23        87   
74.10.04         0        23        21        23         9        17   
74.10.05         0        85        77        87        17        75   
74.10.06         0        23        19        25         2        10   
74.10.10         0        29        29        31        11        30   

          74.10.06  74.10.10  
11.11.01         0         0  
11.11.06         0         0  
11.11.07         0         0  
11.11.14         0         0  
11.11.33         0         0  
...            ...       ...  
74.10.03        25        31  
74.10.04         2        11  
74.10.05        10        30  
74.10.06        10         4  
74.10.10         4        27  

[633 rows x 633 columns]

In [28]:
#calculate the cosine similarity 
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(coocc, coocc))

[[1.         0.97282509 0.12319929 ... 0.05444331 0.06501363 0.05573701]
 [0.97282509 1.         0.07960188 ... 0.0222028  0.02764546 0.02574704]
 [0.12319929 0.07960188 1.         ... 0.28203072 0.19113571 0.12557714]
 ...
 [0.05444331 0.0222028  0.28203072 ... 1.         0.84036147 0.81380594]
 [0.06501363 0.02764546 0.19113571 ... 0.84036147 1.         0.87943456]
 [0.05573701 0.02574704 0.12557714 ... 0.81380594 0.87943456 1.        ]]


In [94]:
df5=(cosine_similarity(coocc, coocc))

In [97]:
df5_matrix=pd.DataFrame(df5)

In [98]:
df5_matrix.to_csv("co_matrix5.csv")

In [96]:
#export the cosine similarity to a .csv
df2_matrix = pd.DataFrame(coocc)
df2_matrix.to_csv("co_matrix4.csv")

In [65]:
#export the co-occurance matrix to a csv
coocc.to_csv("coocc.csv")

In [90]:
# Select an ALI to get recommendations for (#s correspond to columns in the co-occurence matrix )
id = 478
candidate = df2_matrix.iloc[id, :]
candidate


11.11.01    47
11.11.06    11
11.11.07     0
11.11.14    11
11.11.33    22
            ..
74.10.03     0
74.10.04     0
74.10.05     0
74.10.06     0
74.10.10     0
Name: 12.72.11, Length: 633, dtype: int32

In [91]:
# the hight value index: 
top1 = np.argmax(candidate) # one only 
df.columns[top1]

'12.79.00'

In [92]:
# for more than one recommended ALI, adjust the number in 'K'
k = 6
indices = (-candidate).argsort()[:k]
indices

df.columns[indices]

Index(['12.79.00', '12.72.11', '12.72.03', '12.72.08', '12.34.02', '12.24.03'], dtype='object')